version: 2
jobs:
  build:
    working_directory: ~/circleci
    docker:
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: requirements_1-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            pip install poetry
            poetry install
      - save_cache:
          key: requirements_1-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: run tests
          command: poetry run pytest -vv --cov=manageconf tests/
      - run:
          name: generate coverage reports
          command: poetry run coverage html -d artifacts
      - store_artifacts:
          path: artifacts
          destination: cov
